version: "3"

services:
  # payments-api
  payments-api:
    build:
      context: .
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      APP_PORT: "8080"
      OPS_PORT: "8081"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_TIMEOUT: 5
    depends_on:
      - db
  # postgres db
  db:
    image: postgres
    restart: always
    container_name: postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  # pg adminer
  adminer:
    image: adminer
    restart: always
    container_name: adminer-container
    ports:
        - 8085:8080
    links:
      - db:db
